pipeline {
    agent any
    environment {
        FLASK_ENV = 'testing'             // Окружение для Flask
        DATABASE_URL = 'postgresql://sonar:sonar@db:5432/flask_db' // URL базы данных
        SONARQUBE_ENV = 'SonarQube'       // Имя настроенного SonarQube сервера
    }
    stages {

        stage('Checkout Repository') {
            steps {
                // Клонирование репозитория
                git branch: 'feature/lab4-jenkins', url: 'https://github.com/valerizabby/sbt-devops-hw.git'
            }
        }

//         stage('Debugging') {
//             steps {
//                 sh '''
//                     echo "Current working directory:"
//                     pwd
//                     echo "Listing all files:"
//                     ls -R
//                 '''
//             }
//         }

        stage('Updating system') {
            steps {
                sh 'apt-get update'
            }
        }

        stage('Install Dependencies') {
            steps {
                // установка зависимостей для сборки
                sh 'apt install -y python3 python3-pip'
                // Установка зависимостей для тестов
                sh 'apt install -y python3-pytest python3-venv'
                // Зависимость чтобы работал psycopg2
                sh 'apt install -y libpq-dev'

            }
        }
        stage("Build Virtual Environment"){
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r ./lab4/DB/app/requirements.txt
                '''
            }
        }


        stage('Run Unit Tests') {
            steps {
                // Запуск тестов и генерация отчёта покрытия
                sh '''
                    . venv/bin/activate
                    pytest lab4/DB/tests/ --junitxml=test-results.xml
                '''
            }
        }
// pytest ./lab4/DB/app/tests/ --cov=app --cov-report=xml --cov-report=html --junitxml=test-results.xml
            post {
                always {
                    // Публикация отчётов тестов
                    junit 'test-results.xml'
                    publishCoverage adapters: [cobertura('coverage.xml')]
                }
            }
        }
//         stage('Generate Allure Report') {
//             steps {
//                 // Генерация Allure-отчёта
//                 sh '''
//                 pytest sbt-devops-hw/lab4/DB/tests/ --alluredir=allure-results
//                 allure generate --clean allure-results -o allure-report
//                 '''
//             }
//             post {
//                 always {
//                     // Публикация Allure-отчёта в Jenkins
//                     allure includeProperties: false, results: [[path: 'allure-results']]
//                 }
//             }
//         }
//         stage('Static Code Analysis') {
//             steps {
//                 // Анализ кода с помощью SonarQube
//                 withSonarQubeEnv('SonarQube') {
//                     sh '''
//                     sonar-scanner \
//                         -Dsonar.projectKey=flask_app \
//                         -Dsonar.sources=. \
//                         -Dsonar.host.url=http://sonarqube:9000 \
//                         -Dsonar.login=$SONAR_AUTH_TOKEN
//                     '''
//                 }
//             }
//         }
//         stage('Ensure High Test Coverage') {
//             steps {
//                 // Проверка покрытия кода
//                 sh '''
//                 pytest --cov=app --cov-fail-under=90
//                 '''
//             }
//         }
//         stage('Build Docker Image') {
//             steps {
//                 dir("app") {
//                     // Сборка Docker-образа приложения
//                     sh '''
//                     docker build -t flask-postgres-app:latest .
//                     '''
//                 }
//             }
//         }
//         stage('Build And Deploy Application') {
//             steps {
//                 dir("app") {
//                     // Деплой приложения через Ansible или Docker Compose
//                     sh '''
//                     docker-compose down
//                     docker-compose up -d --build
//                     '''
//                 }
//             }
//         }
//     }
    }
    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
