FROM ubuntu:latest

# установим python и pip через докер, потому что установка через playbook заняла КУЧУ ВРЕМЕНИ (хз почему)
RUN apt-get update && apt-get install -y python3 python3-pip

EXPOSE 9999
